### ISSUE TITLE
Initialize V2

### ISSUE THREAD

**Issue by luserx0** [luserx0/configs#3]
### Milestones:
- [ ] Installation script:
  * [ ] Qubes/Linux option
  * [ ] Wayland/X11 option
  * [ ] Software to install
  * [ ] Config install target paths (see #1)
- [ ] i3/sway:
  - [ ] Target systems:
    * [ ] Qubes
    * [ ] KDE 
    * [ ] Barebone
  - [ ] Command line utils:
    * ++
  - [ ] Modular implementation
- [ ] Add signatures and LICENSE
